[package]
name = "megastore_busca_otimizada"
version = "0.1.0"
edition = "2021"

[dependencies]
# petgraph: O motor de grafos
petgraph = "0.6" 

# serde: Para serializar/desserializar (usaremos para carregar dados simulados)
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"